# site properties and page defaults
title: 狼牙战队
subtitle: 
description: 华中科技大学 RoboMaster 狼牙战队
header: images/background.jpg
header-video: images/bgvideo.mp4
footer: images/background.jpg
proofer: false
slogan: 一往无前华科行，气壮山河狼牙名
# site social media and other links
links:
  email: hustrobomaster@163.com
  github: HUSTLYRM
  bilibili: "475402455"
  wechat: https://mp.weixin.qq.com/s/Zrk4PRRGSimJG9bVDj3Zsg
## jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  - scope:
      type: "awards"
    values:
      layout: award
  - scope:
      type: "events"
    values:  
      layout: event
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post
  - scope:
      type: "news"
    values:
      layout: post



collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true
  awards:
    output: true
  news:
    output: true
  projects:
    output: true
  patents:
    output: true
  events:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
